-- SELECT * FROM STAFFS;
-- SELECT * FROM APPLICATIONS;
-- SELECT * FROM ANALYZE;
SELECT * FROM USERS;
-- UPDATE APPLICATIONS SET STATUS = 1;
-- SELECT SYS_CONTEXT('users_ctx','uuid') FROM DUAL;
-- INSERT INTO ANALYZE (a_id, s_id, ISREAD)
-- VALUES (3, 1, 'N');
-- UPDATE ANALYZE SET ISREAD = 'Y' WHERE a_id = 1;
-- GRANT CREDIT_ANALYST_ROLE TO BANKCA;
-- GRANT CREDIT_MANAGER_ROLE TO BANKCM;
-- GRANT CUSTOMER_SERVICE_REPRESENTATIVES_ROLE TO BANKCSR;
-- SELECT * FROM DBA_USERS WHERE USERNAME = 'bankca';
-- DELETE FROM USERS;
-- DELETE FROM STAFFS;
-- DELETE FROM CUSTOMERS;
-- DELETE FROM BANKADM.ANALYZE;
-- set SERVEROUTPUT ON;

-- conn bankca/"@Aa12345678"@localhost:1521/bankpdb;
-- conn bankcm/"@Aa12345678"@localhost:1521/bankpdb;
-- SELECT BANKADM.ANALYZE_POLICY_FUNCTION('','') FROM DUAL;
-- SELECT BANKADM.APPLICATIONS_POLICY_FUNCTION('','') FROM DUAL;
-- SELECT SYS_CONTEXT('SYS_SESSION_ROLES','CREDIT_MANAGER_ROLE') FROM DUAL;
-- SELECT SYS_CONTEXT('SYS_SESSION_ROLES','CUSTOMER_ROLE') FROM DUAL;

UPDATE BANKADM.ANALYZE SET ANALYSIS = 'test';
UPDATE BANKADM.APPLICATIONS SET STATUS = 1
WHERE C_NAME = 'Daniel';

-- ALTER PLUGGABLE DATABASE bankpdb CLOSE IMMEDIATE;
-- ALTER PLUGGABLE DATABASE bankpdb OPEN READ WRITE;

-- SELECT * FROM BANKADM.APPLICATIONS WHERE created_by = '03E5FDBA6A314DA8957209F3AF668E1F';
-- @@insert\\test_process.sql
